---

# configuring upstreams

- name: write upstreams configuration
  become: yes
  template:
    src: "upstream.conf.j2"
    dest: "/etc/nginx/upstreams.d/{{ item.label }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0644"
  with_items: "{{ nginx_upstreams }}"
  notify: nginx - restart
